# ARG var
# ENV var=${var}

ARG version=9.0
FROM odoo:$version

USER root

RUN echo "Asia/shanghai" > /etc/timezone;

# Set OS timezone to China
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

# Set Odoo timezone to China (will be set at startup thanks to Odoo
# parameter substitution)
ENV ODOO_TIMEZONE=Asia/Shanghai

# CN fonts
RUN apt-get update && \
  apt-get -y install ttf-wqy-zenhei
  
# set hosts
RUN copy hosts /etc/hosts \
    copy hostname /etc/hostname



RUN pip install simplejson;

RUN apt-get update && \
    apt-get install -y python-matplotlib emacs-nox git net-tools tree python-pip file nginx python-dev sudo htop locales locales-all wget fonts-dejavu && \
    pip install gevent psycogreen && \
    #update werkzeug to make phantomjs work. See http://odoo-development.readthedocs.io/en/latest/dev/tests/js.html#regular-phantom-js-tests
    pip install werkzeug --upgrade && \
    apt-get install -y npm python-lxml libxml2-dev libxslt1-dev && \
    wget -q -O- https://raw.githubusercontent.com/OCA/pylint-odoo/master/requirements.txt | xargs pip install && \
    # Extra package for pylint-odoo plugin
    npm install -g jshint



# install phantomjs (based on https://hub.docker.com/r/cmfatih/phantomjs/~/dockerfile/ )
ENV PHANTOMJS_VERSION 1.9.8

RUN \
  apt-get install -y libfreetype6 libfontconfig && \
  mkdir -p /srv/var && \
  wget -q --no-check-certificate -O /tmp/phantomjs-$PHANTOMJS_VERSION.tar.gz https://github.com/ariya/phantomjs/archive/$PHANTOMJS_VERSION.tar.gz && \
  tar -xzf /tmp/phantomjs-$PHANTOMJS_VERSION.tar.gz -C /tmp && \
  rm -f /tmp/phantomjs-$PHANTOMJS_VERSION.tar.gz && \
  mv /tmp/phantomjs-$PHANTOMJS_VERSION/ /srv/var/phantomjs && \
  ln -s /srv/var/phantomjs/bin/phantomjs /usr/bin/phantomjs && \
  git clone https://github.com/n1k0/casperjs.git /srv/var/casperjs && \
  ln -s /srv/var/casperjs/bin/casperjs /usr/bin/casperjs && \
  apt-get autoremove -y && \
  apt-get clean all

# fix access issue with nginx
RUN touch /var/log/nginx/error.log && \
    touch /var/log/nginx/access.log && \
    chown odoo:odoo -R /var/log/nginx && \
    chown odoo:odoo -R /var/lib/nginx/


ENV BUILD_DATE=2016_11_03
ARG version=9.0

RUN git clone -b $version https://github.com/OCA/runbot-addons.git /mnt/runbot-addons && \
    # pip install --upgrade pylint && \
    # pip install --upgrade git+https://github.com/oca/pylint-odoo.git && \
    git clone https://github.com/odoo/odoo-extra.git /mnt/odoo-extra && \
    rm -rf /mnt/odoo-extra/website_twitter_wall
    copy runbot.py /mnt/odoo-extra/runbot/

# grant access to work dir
RUN chown odoo:odoo -R /mnt/odoo-extra/runbot/static/

RUN true && \
    # always close cron db connnections
    sed -i "s/if len(db_names) > 1:/if True:/" /usr/lib/python2.7/dist-packages/openerp/service/server.py && \
    # auto_reload
    sed -i -e "s/auto_reload = True/; auto_reload = True/" /etc/odoo/openerp-server.conf && \
    # limits:
    sed -i -e "s/; limit_time_cpu.*/limit_time_cpu = 300/" /etc/odoo/openerp-server.conf && \
    sed -i -e "s/; limit_time_real.*/limit_time_real = 600/" /etc/odoo/openerp-server.conf && \
    # addons_path:
    sed -i -e "s;addons_path.*;addons_path = /mnt/odoo-extra,/mnt/extra-addons,/mnt/runbot-addons,/usr/lib/python2.7/dist-packages/openerp/addons;" /etc/odoo/openerp-server.conf

VOLUME ["/mnt/odoo-extra", "/mnt/runbot-addons"]

CMD ["openerp-server", "--database=runbot", "--db-filter=^runbot$", "--workers=2"]

USER odoo
